### PR TITLE
Changed parameters of example to work with default settings

### PR DESCRIPTION
**Pull request by YacobBY**
These settings will make it work out of the box with most printers. I was scratching my head a little wondering why it didn't work initially and this should help more people get it working out of the box.

### CODE REVIEW

**Comment by kanryu** [comment]
The codebar-> codabar type is as you indicated. However, with regard to the printer port number, the default port of the SATO printer is 1024 if my understanding is correct. Of course it is possible to change it to 9100 because it is a port number, but I have not confirmed it.

**Comment by YacobBY** [comment]
I am currently working with a M84Pro-2 so maybe my settings are just very different. Better to keep the default at 1024 then. All functions work well with my printer as well, I'm assuming that the programming guide https://d2n1rly8br52rx.cloudfront.net/resources/files/E-Pro-Programming-Reference.pdf?mtime=20180811212200 is universal for all SATO printers. I might write some extra code to print BMP images and submit here later if I can get it working. Anyways thanks for the library it's a great help.

**Comment by kanryu** [comment]
Now, please update this pull request with it returned to 1024.

In addition, the specifications of SBPL commands differ considerably depending on the model of SATO printer. In particular, the specifications for printing user-defined bitmaps were quite different from the English specifications available on the Internet. Please let me know if there is a command that does not work properly with your printer (this request is not directly related to the pull request)

**Comment by kanryu** [comment]
Thanks!

**Pull request merged**
